#!/bin/bash

# Colours - assumes that base16 colours are defined in ~/.Xresources
eval $(grep -o -E 'base0[0-9|A-F] #[0-9|a-z|A-Z]*' ~/.Xresources | awk -F ' ' '{print $1"=\""$2"\""}')

# Monitor 
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config border_width         2
bspc config window_gap           0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color         "${base01}"
bspc config active_border_color         "${base00}"
bspc config focused_border_color 	"${base0D}"
bspc config presel_feedback_color 	"${base0E}"

# Rules
#bspc rule -a Thunar pseudo_tiled=on

# General
hsetroot -solid "${base00}"
xsetroot -cursor_name left_ptr
polybar example &
sxhkd &
vmware-user-suid-wrapper
dunst

