#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color         "#282a2e"
bspc config focused_border_color 	"#81a2be"

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# TODO: Handle these properly
hsetroot -solid "#1d1f21"
xsetroot -cursor_name left_ptr
polybar example &
sxhkd &
vmware-user-suid-wrapper
dunst

