#!/bin/bash

cd $(dirname $0)
source ./config

if [ "$(pgrep -u $(whoami) -x tab | wc -l)" -gt 2 ]; then
  printf "%s\n" "The tab is already running." >&2
  exit 1
fi

while read line; do
  parts=($line)
  case ${parts[0]} in
    desktop_focus)
      layout=$(bspc query -T -d ${parts[2]}| jq .userLayout -r)
      if [ "$layout" == "tiled" ]; then
        kill -15 $(pgrep tab_bar -a | grep ${parts[1]} | cut -d ' ' -f 1)
      elif [ $(pgrep tab_bar -a | grep ${parts[2]} | wc -l) -eq 0 ]; then
        ./tab_bar ${parts[1]} ${parts[2]} &
      fi
      ;;
    desktop_layout)
      case ${parts[3]} in
        monocle)
          if [ $(pgrep tab_bar -a | grep ${parts[2]} | wc -l) -eq 0 ]; then
            ./tab_bar ${parts[1]} ${parts[2]} &
          fi
          ;;
        tiled)
          kill -15 $(pgrep tab_bar -a | grep ${parts[2]} | cut -d ' ' -f 1)
          ;;
      esac
      ;;
    desktop_transfer)
      kill -15 $(pgrep tab_bar -a | grep ${parts[2]} | cut -d ' ' -f 1)
      ./tab_bar ${parts[3]} ${parts[2]} &
      ;;
  esac
done < <(bspc subscribe desktop_focus desktop_layout desktop_transfer)
