#!/bin/bash
#
# Modified from http://colby.id.au/calculating-cpu-usage-from-proc-stat
#

total () {
  TOTAL=0
  for i in $@; do
    let "TOTAL+=${i}"
  done
  echo $TOTAL
}

P_CPU=( $(cat /proc/stat | grep '^cpu ') )
unset P_CPU[0]
P_IDLE=${P_CPU[4]}
P_TOTAL=$(total ${P_CPU[@]})

sleep 1

CPU=( $(cat /proc/stat | grep '^cpu ') )
unset CPU[0]
IDLE=${CPU[4]}
TOTAL=$(total ${CPU[@]})

let "C_IDLE=${IDLE}-${P_IDLE}"
let "C_TOTAL=${TOTAL}-${P_TOTAL}"
let "C_USAGE=(1000*(${C_TOTAL}-${C_IDLE})/${C_TOTAL}+5)/10"

printf "\uf05b %3.0f%\n" $C_USAGE

if [[ $C_USAGE -gt 80 ]]; then
    echo "#cf6a4c\n"  # Red
    exit 0;
elif [[ $C_USAGE -gt 60 ]]; then
    echo "#d8ad4c\n"  # Yellow
    exit 0;
fi
