#!/bin/bash
#
#  TODO: Add click actions
#

dt0=$(date '+%a')
dt1=$(date '+%d')
dt2=$(date '+%b')
dt3=$(date '+%H')
dt4=$(date '+%M')

echo "<span>  $dt1 $dt2 </span>$dt3<span foreground='#969896'>:</span>$dt4"
