#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE_E="${BLOCK_INSTANCE:-eth0}"
INTERFACE_W="${BLOCK_INSTANCE:-wlp2s0}"


LINE=""

#------------------------------------------------------------------------
# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
#([[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
#    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit


if [[ -d /sys/class/net/${INTERFACE_W}/wireless ]] &&
    [[ "$(cat /sys/class/net/$INTERFACE_W/operstate)" == 'up' ]]; then
  QUALITY=$(grep $INTERFACE_W /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
  LINE+="  $QUALITY%"
fi

#------------------------------------------------------------------------

if [[ -d /sys/class/net/${INTERFACE_E}/device ]] &&
    [[ "$(cat /sys/class/net/$INTERFACE_E/operstate)" == 'up' ]]; then
  LINE+=" "
elif [[ "$(cat /sys/class/net/en*/operstate)" == 'up' ]]; then
  LINE+=" "
fi

#------------------------------------------------------------------------

echo $LINE # full text
echo $LINE # short text

# color
#if [[ $QUALITY -ge 70 ]]; then
#    echo "#99ad6a"
#elif [[ $QUALITY -lt 70 ]]; then
#    echo "#ffd574"
#elif [[ $QUALITY -lt 50 ]]; then
#    echo "#d8ad4c"
#elif [[ $QUALITY -lt 30 ]]; then
#    echo "#f79274"
#fi


