#!/bin/bash
#
# get active window with xprop and cut
# using tr to translate some bad characters "&<>" and using python to have more control on where to cut/truncate

WIN="$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | sed -un 's/.*\(0x.*\)/\1/p')| awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)"
if [ -n "$WIN" ];
then
    # add pango formatting
    echo "<span weight='medium'> "$WIN" </span>"
else
    exit 0
fi

# add some mouse actions
case $BLOCK_BUTTON in
    1) i3-msg layout tabbed ;; # left click tabbed layout
    2) i3-msg layout stacked ;; # middle click stacked
    3) i3-msg layout toggle split ;; # right click
    4) rofi -width 45 -show window ;; # scroll down jump to window
    5) rofi-getwindow ;; # scroll up move window to current
esac
