#!/bin/bash

# menu icon
echo -en "\uf00b "
#  ☰  

# open or close stalonetray
stray() {
  if [[  $(pgrep -cx stalonetray) -eq 0 ]] ; then
    X=40
    i3-msg -t get_outputs | jq -c '.[]' | while read i; do
      if [[ `echo $i | jq '.active'` == 'true' ]]; then
        let X+=`echo $i | jq '.rect.x'`
      fi
    done
    i3-msg exec "stalonetray --geometry 1x1-$X+31" >/dev/null &
  else
    PID=`pgrep -x stalonetray`
    if [[ $? -eq 0 ]]; then
      kill -s TERM $PID
    fi
  fi
}

# mouse buttons
case $BLOCK_BUTTON in
    1) stray ;; # left click - stalonetray
esac
