#! /bin/sh

cd $(dirname $0)
source ./config

num_mon=$(bspc query -M | wc -l)
chord=0

while read -r line ; do
  case $line in
    K*)
      item=${line#?}
      case ${item} in
        H*) # Key binding
          # What we should really do is read the line above the chord in sxhkdrc
          key_binding=${item#?}
          case ${key_binding} in
            "super + shift + Escape")
              sxhkd="system: (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (shift+s) shutdown"
              ;;
            *)
              sxhkd="Unknown chord"
              ;;
          esac
          ;;
        B*) # Begin chain
          chord=1
          ;;
        E*) # End chain
          chord=0
          ;;
        C*) # Command
          ;;
        T*) # Timeout
          ;;
      esac
      ;;
    S*)
      # system info (conky)
      sys_infos="%{r}${line#?}"
      ;;
    T*)
      # xtitle output
      if [ -z "${line#?}" ]; then
        title=""
      else
        title=" | %{F$FOREGROUND}%{B$BACKGROUND} ${line#?} %{B-}%{F-}"
      fi
      ;;
    W*)
      # bspwm's state
      wm=
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [mM]*)
            case $item in
              m*)
                # monitor
                FG=$FOREGROUND
                BG=$BACKGROUND
                on_focused_monitor=
                ;;
              M*)
                # focused monitor
                FG=$FOREGROUND
                BG=$BACKGROUND
                on_focused_monitor=1
                ;;
            esac
            [ $num_mon -lt 2 ] && shift && continue
            wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
            ;;
          [fFoOuU]*)
            case $item in
              [OFU]*)
                if [ "$on_focused_monitor" ] ; then
                  # focused free desktop
                  FG=$BACKGROUND
                  BG=$BLUE
                  UL=$BG
                else
                  # active free desktop
                  FG=$FOREGROUND
                  BG=$BACKGROUND_ALT
                  UL=$BG
                fi
                ;;
              f*)
                # free desktop
                FG=$FOREGROUND
                BG=$BACKGROUND
                UL=$BG
                ;;
              o*)
                # occupied desktop
                FG=$FOREGROUND
                BG=$BACKGROUND_ALT
                UL=$BG
                ;;
              u*)
                # urgent desktop
                FG=$BACKGROUND
                BG=$RED
                UL=$BG
                ;;
            esac
            wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
            ;;
          #[LTG]*)
          #  # layout, state and flags
          #  wm="${wm}%{F$FOREGROUND}%{B$BACKGROUND} ${name} %{B-}%{F-}"
          #  ;;
        esac
        shift
      done
      ;;
  esac
  if [ $chord -eq 0 ]; then
    printf "%s\n" "%{l}${wm}${title}%{c}%{r}${sys_infos}"
  else
    printf "%s\n" "%{l}%{F${BACKGROUND}}%{B${YELLOW}} ${sxhkd} %{B-}%{F-}%{c}%{r}${sys_infos}"
  fi
done
