#!/bin/bash

cd $(dirname $0)
source ./config

if [ -n "$(pgrep -u $(whoami) -x lemonbar)" ]; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

PANEL_FIFO="$(mktemp -d)/panel"
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

cat "$SXHKD_FIFO" | while read -r line; do echo "K$line" > "$PANEL_FIFO"; done &
xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
# NOTE: Pulseaudio can crash conky due to sleep/wake? lets just bring it back
until conky -c ./conkyrc > "$PANEL_FIFO"; do echo "conky crashed" >&2; sleep 1; done &
bspc subscribe report > "$PANEL_FIFO" &

./panel_bar < "$PANEL_FIFO" \
  | lemonbar \
    -a 32 \
    -n "$NAME" \
    -g "$GEOMETRY" \
    -o -10 \
    -f "$FONT1" \
    -o -14 \
    -f "$FONT2" \
    -o -14 \
    -f "$FONT3" \
    -o -14 \
    -f "$FONT4" \
    -F "$FOREGROUND" \
    -B "$BACKGROUND" \
  | sh &

for i in $(xdo id -m -a "$NAME"); do
  xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$i"
done

wait
